site_name: RECAST
site_url: https://wogra-ag.github.io/recast-docs
repo_url: https://github.com/WOGRA-AG/RECAST
nav:
  - Overview: index.md
theme:
  name: material
  logo: assets/logos/recast_logo_white.png
  favicon: assets/logos/favicon.svg
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wogra-ag/posts/?feedView=all
    - icon: fontawesome/brands/github
      link: https://github.com/WOGRA-AG
    - icon: fontawesome/solid/globe
      link: https://wogra.com
    - icon: fontawesome/solid/envelope
      link: mailto:info@wogra.com

extra_css:
  - stylesheets/extra.css

copyright: <a href="https://wogra.com/impressum/">Impressum</a>
